title: Danila Kossygin # name (or website title) 
logo: "/images/logo.png?raw=true" # your photo (or logo)
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>TEST<br>
  Second description 
  <br>TEST<br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
theme: jekyll-theme-minimal
